POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "HP2",
    "price": 2992,
    "description": "Great job!2"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/0.98622279686549294444444

###
PUT http://localhost:3000/products/0.8805548995552908
Content-Type: application/json

{
    "price": 499
}

###
DELETE http://localhost:3000/products/2222222